import React, {useEffect,useState} from 'react';
import {api} from '../src/api.js';
const modules=[['overview','Overview'],['products','Products, inventory & categories'],['orders','Orders & payments'],['users','Customers, carts & wishlists'],['reviews','Reviews'],['banners','Banners'],['family','RAJO family'],['blogs','Blog posts'],['media','Image library & uploads'],['coupons','Discount codes'],['enquiries','Enquiries'],['email-queue','Email notifications'],['settings','COD, shipping & store settings']];
export function AdminAccess(){
 const [admins,setAdmins]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>api('/admin/users').then(r=>setAdmins(r.items.filter(u=>u.role==='admin'))).catch(e=>setError(e.message));
 useEffect(()=>{load();},[]);
 async function save(user){setBusy(true);setError('');setNotice('');try{await api('/admin/users/'+user._id,{method:'PATCH',body:{role:'admin',status:user.status,adminPermissions:user.adminPermissions||[]}});setNotice('Access saved. This administrator must sign in again.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="classic-panel settings-panel"><h2>Administrator access</h2><p>Nishant has permanent full access. Choose the sections each other administrator can use. Related tabs share the permission shown below; only the owner can change administrator roles and access.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{admins.map(user=><article key={user._id} style={{borderTop:'1px solid #ecd9cb',padding:'20px 0'}}><h3>{user.email}</h3>{user.email==='nishant@gmail.com'?<p>Owner · All sections enabled</p>:<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:16}}>{modules.map(([key,label])=><label key={key} style={{display:'flex',gap:10,alignItems:'center'}}><input type="checkbox" checked={(user.adminPermissions||[]).includes(key)} onChange={e=>setAdmins(admins.map(u=>u._id!==user._id?u:{...u,adminPermissions:e.target.checked?[...(u.adminPermissions||[]),key]:(u.adminPermissions||[]).filter(x=>x!==key)}))}/>{label}</label>)}</div><button className="primary" disabled={busy} onClick={()=>save(user)} style={{marginTop:20}}>Save access for {user.email}</button></>}</article>)}</section>;
}
