import React,{useEffect,useState} from 'react';
import {api} from '../src/api.js';
export function EmailQueue(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>api('/admin/email-queue').then(setData).catch(e=>setError(e.message));
 useEffect(()=>{load();},[]);
 async function toggle(){setBusy(true);setError('');try{await api('/admin/email-queue',{method:'PATCH',body:{enabled:!data.enabled}});await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="classic-panel settings-panel"><h2>New-product email notifications</h2><p>From: info.rajothreads@gmail.com</p><button className="primary" role="switch" aria-checked={Boolean(data?.enabled)} aria-label="New-product email notifications" disabled={!data||busy} onClick={toggle}>{busy?'Saving…':data?.enabled?'Enabled — turn off':'Disabled — turn on'}</button><p>Turning off pauses new-product emails and pending deliveries. Turning on resumes the queue, including products published while disabled. An email already being sent may still arrive.</p><p>{!data?'Loading status…':!data.enabled?'Delivery disabled by administrator.':data.ready?'Automatic delivery is configured. New products are queued on first publication.':'Delivery paused: configure the sender’s Gmail App Password.'}</p><p>Checks run every 15 minutes in small batches, with at most 100 attempts per 24 hours. Unsubscribed and blocked customers are skipped.</p><button className="secondary" onClick={load}>Refresh status</button>{error&&<p role="alert">{error}</p>}<div className="compact-stats">{['pending','sent','failed','skipped'].map(status=><article key={status}><span>{status}</span><strong>{data?.counts.find(r=>r._id===status)?.count||0}</strong></article>)}</div><div className="studio-table-wrap"><table><thead><tr><th>Product</th><th>Status</th><th>Created</th><th>Delivery note</th></tr></thead><tbody>{data?.items.map(row=><tr key={row._id}><td>#{row.productId}</td><td>{row.status}</td><td>{new Date(row.createdAt).toLocaleDateString('en-IN')}</td><td>{row.error||'—'}</td></tr>)}</tbody></table></div><p>Failed or interrupted deliveries are held for review. Editing a product does not resend it.</p></section>;
}
